###
    # Customer Login
###
POST http://localhost:3000/api/auth/customer/login
Content-Type: application/json

{
    "phone" : "8850664191"
}


###
    # Verify OTP
###
POST http://localhost:3000/api/auth/customer/verify-otp
Content-Type: application/json

{
    "phone" : "8850664191",
    "otp" : "1790"
}


### Registration
POST http://127.0.0.1:3000/api/auth/customer/register
Content-Type: application/json

{
    "first_name": "Tes",
    "last_name": "TEst",
    "email": "test@joshfuels.com",
    "company": "TYS",
    "phone": "9210129012",
    "accept_term": "true"
}

### Get Profile
GET http://127.0.0.1:3000/api/auth/customer/getProfile
Content-Type: application/json
Authorization: Bearer 

### Update Profile
POST http://127.0.0.1:3000/api/auth/customer/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTY3NjkxMDAsImV4cCI6MTY5NzM3MzkwMH0.K0NRx1fEC8L0186YPz8OPKjftNEtXuWp3RUtqDR6KEQ

{    
    "email": "admin@joshfuels.com"
}

### Update Profile Photo 
POST http://127.0.0.1:3000/api/auth/customer/updatePhoto
Content-Type: application/json
Authorization: Bearer 

{    
    "first_name": "Anil"
}


### Add Address
POST http://localhost:3000/api/auth/customer/add-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4.eyJ1c2VySWQiOiI2NTFmYjNlODQxZWRlNjgxYzE2Y2Q3NTkiLCJmaXJzdF9uYW1lIjoiVGVzIiwibGFzdF9uYW1lIjoiVEVzdCIsImVtYWlsIjoidGVzdEBqb3NoZnVlbHMuY29tIiwicGhvbmUiOiI5MjEwMTI5MDEyIiwiaWF0IjoxNjk2NTc2NDg5LCJleHAiOjE2OTcxODEyODl9.CUa2Wi7sJKRuTp7NZVJ6kCN9Z3WgCQsR9FK5GoDunbg

{
    "address_type" : "Office", 
    "address_1" : "S-58, Haware Fantasia, Behind Inorbit Mall", 
    "area" : "Vashi", 
    "city" : "Navi Mumbai", 
    "pincode" : "123455", 
    "state" : "Maharashtra", 
    "country" : "India"
}

### Get Address
GET http://localhost:3000/api/auth/customer/get-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

### Update Address
POST http://localhost:3000/api/auth/customer/update-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "address_id" : "650191993bd8b22339022421",
    "address_type" : "Office", 
    "address_1" : "S-58, Haware Fantasia, Behind Inorbit Mall", 
    "area" : "Vashi", 
    "city" : "Navi Mumbai", 
    "pincode" : "000000", 
    "state" : "Maharashtra", 
    "country" : "India"
}

### Deleted Address 
DELETE http://localhost:3000/api/auth/customer/delete-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "address_id" : "650191c73bd8b22339022427"
}

### Add Device
POST http://localhost:3000/api/auth/customer/add-device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "name" : "shivam's iPhone",
    "type" : "iOS",
    "version" : "17.0.1"
}

### Fetch data 
Get http://localhost:3000/api/auth/customer/userdata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

### LogOut
POST http://localhost:3000/api/auth/customer/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4.eyJ1c2VySWQiOiI2NTFmYjNlODQxZWRlNjgxYzE2Y2Q3NTkiLCJmaXJzdF9uYW1lIjoiVGVzIiwibGFzdF9uYW1lIjoiVEVzdCIsImVtYWlsIjoidGVzdEBqb3NoZnVlbHMuY29tIiwicGhvbmUiOiI5MjEwMTI5MDEyIiwiaWF0IjoxNjk2NTc2NDg5LCJleHAiOjE2OTcxODEyODl9.CUa2Wi7sJKRuTp7NZVJ6kCN9Z3WgCQsR9FK5GoDunbg

### Send OTP to email 
POST http://localhost:3000/api/auth/customer/send-otp
Content-Type: application/json

{
    "email" : "shivamrvgupta@gmail.com"
}

########## Branch API ##########

### 
    # Branch Details
###
GET  http://localhost:3000/api/auth/branch/nearest-branch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

### 
    # Nearest Branch Product
###
GET  http://localhost:3000/api/auth/branch/branchProducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4


########## Cart API ##########

### 
    # Show Cart
###
GET  http://localhost:3000/api/auth/cart/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

### 
    # Add To Cart
###
POST http://localhost:3000/api/auth/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4 

{
    "product" : "64f6da85ed30c8f3d5765043",
    "quantity" : "15"
}

### 
    # Update Cart Data
###
POST http://localhost:3000/api/auth/cart/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4 

{
    "cart_id" : "6509f70778e25cf42012d7e8",
    "product_id" : "64f6da5aed30c8f3d5765007",
    "quantity" : 91
}

### 
    # Delete Single Cart Data
###
POST http://localhost:3000/api/auth/cart/delete-item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "cart_id" : "6509f70778e25cf42012d7e8",
    "product_id" : "64f6da5aed30c8f3d5765007"
}

### 
    # Delete Cart Data
###
DELETE http://localhost:3000/api/auth/cart/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "cart_id" : "6511567d24cf23e69c137a41",
    "product_id" : "64f6da85ed30c8f3d5765043"
}


###         # Order API  #       ###
## CREATE ORDER 
POST http://localhost:3000/api/auth/order/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "address_id": "65003ac3957a312ef073de8e",
    "cart_id": "65117f8eba855992eeef6515",
    "delivery_date": "29/09/2023",
    "delivery_time": "2:00 - 10:00",
    "payment_method": "Cash on Delivery",
    "note": "Keep the Diesels extra on;y",
    "total_price" : 12340,
    "coupon_discount" : 100,
    "delivery_fee" : 300,
    "grand_total": 1334

}


### GeT ORDER 
GET http://localhost:3000/api/auth/order/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

### GeT Single ORDER 
GET http://localhost:3000/api/auth/order/get-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "order_id" : "100002"
}

### Cancel order
POST http://localhost:3000/api/auth/order/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "order_id" : "100002"
}

### Update order
POST http://localhost:3000/api/auth/order/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NzY0NjY1LCJleHAiOjE2OTczNjk0NjV9.NNdM9rWGbM4MNirKXc-o9aFLYKbGpSECsalPF5fBCN4

{
    "order_id" : "100002",
    "product_id" : "64f6da85ed30c8f3d5765043",
    "quantity" : 100,
    "total_price" : 12385,
    "grand_total" : 16446.88
}   

### Send Email
POST http://localhost:3000/api/auth/customer/send-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6InJ2c2hpdmFtc2FodS4xMjIyQGdtYWlsLmNvbSIsInBob25lIjoiODg1MDY2NDE5MSIsImlhdCI6MTY5Njg0Njc3NSwiZXhwIjoxNjk3NDUxNTc1fQ.I49vz4a5MGMrelx8lw6sgdiz-toW0HBPBMNDDq3_VNI
