###
    # Customer Login
###
POST http://3.108.237.66/api/auth/customer/login
Content-Type: application/json

{
    "phone" : "9870878040"
}


###
    # Verify OTP
###
POST http://3.108.237.66/api/auth/customer/verify-otp
Content-Type: application/json

{
    "phone" : "9870878040",
    "otp" : "5144"
}


### Registration
POST http://127.0.0.1:3000/api/auth/customer/register
Content-Type: application/json

{
    "first_name": "Tes",
    "last_name": "TEst",
    "email": "test@joshfuels.com",
    "company": "TYS",
    "phone": "9210129012",
    "accept_term": "true"
}

### Get Profile
GET http://127.0.0.1:3000/api/auth/customer/getProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NTkyMTgyLCJleHAiOjE2OTcxOTY5ODJ9.3j4YMPEa8k9ZC4EjrSUAypj9AAIKF304CooXeWI8EhA

### Update Profile
POST http://127.0.0.1:3000/api/auth/customer/updateProfile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NTkyMTgyLCJleHAiOjE2OTcxOTY5ODJ9.3j4YMPEa8k9ZC4EjrSUAypj9AAIKF304CooXeWI8EhA

{    
    "first_name": "Anil"
}

### Update Profile Photo 
POST http://127.0.0.1:3000/api/auth/customer/updatePhoto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGZkYzNhZmZmOWQ2MjgyYWM3ZTU0MDkiLCJmaXJzdF9uYW1lIjoiQW5pbCIsImxhc3RfbmFtZSI6Ikd1cHRhIiwiZW1haWwiOiJhbmlsZ3VwdGFAZGlzcG9zdGFibGUuY29tIiwicGhvbmUiOiI5ODcwODc4MDQwIiwiaWF0IjoxNjk2NTkyMTgyLCJleHAiOjE2OTcxOTY5ODJ9.3j4YMPEa8k9ZC4EjrSUAypj9AAIKF304CooXeWI8EhA

{    
    "first_name": "Anil"
}


### Add Address
POST http://3.108.237.66/api/auth/customer/add-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYjNlODQxZWRlNjgxYzE2Y2Q3NTkiLCJmaXJzdF9uYW1lIjoiVGVzIiwibGFzdF9uYW1lIjoiVEVzdCIsImVtYWlsIjoidGVzdEBqb3NoZnVlbHMuY29tIiwicGhvbmUiOiI5MjEwMTI5MDEyIiwiaWF0IjoxNjk2NTc2NDg5LCJleHAiOjE2OTcxODEyODl9.CUa2Wi7sJKRuTp7NZVJ6kCN9Z3WgCQsR9FK5GoDunbg

{
    "address_type" : "Office", 
    "address_1" : "S-58, Haware Fantasia, Behind Inorbit Mall", 
    "area" : "Vashi", 
    "city" : "Navi Mumbai", 
    "pincode" : "123455", 
    "state" : "Maharashtra", 
    "country" : "India"
}

### Get Address
GET http://3.108.237.66/api/auth/customer/get-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

### Update Address
POST http://3.108.237.66/api/auth/customer/update-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "address_id" : "650191993bd8b22339022421",
    "address_type" : "Office", 
    "address_1" : "S-58, Haware Fantasia, Behind Inorbit Mall", 
    "area" : "Vashi", 
    "city" : "Navi Mumbai", 
    "pincode" : "000000", 
    "state" : "Maharashtra", 
    "country" : "India"
}

### Deleted Address 
DELETE http://3.108.237.66/api/auth/customer/delete-address
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "address_id" : "650191c73bd8b22339022427"
}

### Add Device
POST http://3.108.237.66/api/auth/customer/add-device
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "name" : "shivam's iPhone",
    "type" : "iOS",
    "version" : "17.0.1"
}

### Fetch data 
Get http://3.108.237.66/api/auth/customer/userdata
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

### LogOut
POST http://3.108.237.66/api/auth/customer/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTFmYjNlODQxZWRlNjgxYzE2Y2Q3NTkiLCJmaXJzdF9uYW1lIjoiVGVzIiwibGFzdF9uYW1lIjoiVEVzdCIsImVtYWlsIjoidGVzdEBqb3NoZnVlbHMuY29tIiwicGhvbmUiOiI5MjEwMTI5MDEyIiwiaWF0IjoxNjk2NTc2NDg5LCJleHAiOjE2OTcxODEyODl9.CUa2Wi7sJKRuTp7NZVJ6kCN9Z3WgCQsR9FK5GoDunbg

### Send OTP to email 
POST http://3.108.237.66/api/auth/customer/send-otp
Content-Type: application/json

{
    "email" : "shivamrvgupta@gmail.com"
}

########## Branch API ##########

### 
    # Branch Details
###
GET  http://3.108.237.66/api/auth/branch/nearest-branch
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

### 
    # Nearest Branch Product
###
GET  http://3.108.237.66/api/auth/branch/branchProducts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM


########## Cart API ##########

### 
    # Show Cart
###
GET  http://3.108.237.66/api/auth/cart/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

### 
    # Add To Cart
###
POST http://3.108.237.66/api/auth/cart/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM 

{
    "product" : "64f6da85ed30c8f3d5765043",
    "quantity" : "15"
}

### 
    # Update Cart Data
###
POST http://3.108.237.66/api/auth/cart/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM 

{
    "cart_id" : "6509f70778e25cf42012d7e8",
    "product_id" : "64f6da5aed30c8f3d5765007",
    "quantity" : 91
}

### 
    # Delete Single Cart Data
###
POST http://3.108.237.66/api/auth/cart/delete-item
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "cart_id" : "6509f70778e25cf42012d7e8",
    "product_id" : "64f6da5aed30c8f3d5765007"
}

### 
    # Delete Cart Data
###
DELETE http://3.108.237.66/api/auth/cart/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "cart_id" : "6511567d24cf23e69c137a41",
    "product_id" : "64f6da85ed30c8f3d5765043"
}


###         # Order API  #       ###
## CREATE ORDER 
POST http://3.108.237.66/api/auth/order/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "address_id": "65003ac3957a312ef073de8e",
    "cart_id": "65117f8eba855992eeef6515",
    "delivery_date": "29/09/2023",
    "delivery_time": "2:00 - 10:00",
    "payment_method": "Cash on Delivery",
    "note": "Keep the Diesels extra on;y",
    "total_price" : 12340,
    "coupon_discount" : 100,
    "delivery_fee" : 300,
    "grand_total": 1334

}


### GeT ORDER 
GET http://3.108.237.66/api/auth/order/get
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

### GeT Single ORDER 
GET http://3.108.237.66/api/auth/order/get-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "order_id" : "100002"
}



### Cancel order
POST http://3.108.237.66/api/auth/order/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "order_id" : "100002"
}

### Update order
POST http://3.108.237.66/api/auth/order/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGM5NjMxNzhmNWJmMTI2Njc3YzI0MmEiLCJmaXJzdF9uYW1lIjoiU2hpdmFtIiwibGFzdF9uYW1lIjoiR3VwdGEiLCJlbWFpbCI6ImFkbWluQGpvc2hmdWVscy5jb20iLCJwaG9uZSI6Ijg4NTA2NjQxOTEiLCJpYXQiOjE2OTU4ODQ3MTYsImV4cCI6MTY5NjQ4OTUxNn0.0q69aDajlsCa1fvyurHIH_Wle5eUDFoONSMu_jfRbiM

{
    "order_id" : "100002",
    "product_id" : "64f6da85ed30c8f3d5765043",
    "quantity" : 100,
    "total_price" : 12385,
    "grand_total" : 16446.88
}   